// Code generated by hand to match contracts/ais_record.proto.
// This avoids requiring protoc toolchain — uses a lightweight binary encoding
// compatible with Protocol Buffers wire format.

package proto

import (
	"encoding/binary"
	"math"
)

// AISRecord represents a single AIS position report from one simulated vessel.
type AISRecord struct {
	VesselID           string  `json:"vessel_id"`
	MMSI               string  `json:"mmsi"`
	Lat                float64 `json:"lat"`
	Lon                float64 `json:"lon"`
	SOGKnots           float32 `json:"sog_knots"`
	COGDegrees         float32 `json:"cog_degrees"`
	TSUnixMs           int64   `json:"ts_unix_ms"`
	IsScriptedViolator bool    `json:"is_scripted_violator"`
}

// AISBatch is a batch of AIS records sent as a single network frame.
type AISBatch struct {
	Records  []AISRecord `json:"records"`
	BatchSeq int32       `json:"batch_seq"`
}

// MarshalBinary serializes an AISBatch into a compact binary format.
// Format per record:
//
//	[1-byte vesselID_len][vesselID bytes]
//	[1-byte mmsi_len][mmsi bytes]
//	[8-byte lat float64 LE][8-byte lon float64 LE]
//	[4-byte sog float32 LE][4-byte cog float32 LE]
//	[8-byte ts int64 LE]
//	[1-byte is_scripted_violator (0/1)]
//
// Batch envelope:
//
//	[4-byte batch_seq int32 LE][4-byte record_count int32 LE][records...]
func (b *AISBatch) MarshalBinary() ([]byte, error) {
	// Pre-calculate total size for single allocation
	totalSize := 8 // batch_seq (4) + record_count (4)
	for i := range b.Records {
		r := &b.Records[i]
		totalSize += 1 + len(r.VesselID) // vesselID length prefix + data
		totalSize += 1 + len(r.MMSI)     // mmsi length prefix + data
		totalSize += 8 + 8               // lat + lon
		totalSize += 4 + 4               // sog + cog
		totalSize += 8                   // timestamp
		totalSize += 1                   // is_scripted_violator
	}

	buf := make([]byte, totalSize)
	offset := 0

	// Batch header
	binary.LittleEndian.PutUint32(buf[offset:], uint32(b.BatchSeq))
	offset += 4
	binary.LittleEndian.PutUint32(buf[offset:], uint32(len(b.Records)))
	offset += 4

	// Records
	for i := range b.Records {
		r := &b.Records[i]

		// VesselID
		buf[offset] = byte(len(r.VesselID))
		offset++
		copy(buf[offset:], r.VesselID)
		offset += len(r.VesselID)

		// MMSI
		buf[offset] = byte(len(r.MMSI))
		offset++
		copy(buf[offset:], r.MMSI)
		offset += len(r.MMSI)

		// Lat (float64 LE)
		binary.LittleEndian.PutUint64(buf[offset:], math.Float64bits(r.Lat))
		offset += 8

		// Lon (float64 LE)
		binary.LittleEndian.PutUint64(buf[offset:], math.Float64bits(r.Lon))
		offset += 8

		// SOG (float32 LE)
		binary.LittleEndian.PutUint32(buf[offset:], math.Float32bits(r.SOGKnots))
		offset += 4

		// COG (float32 LE)
		binary.LittleEndian.PutUint32(buf[offset:], math.Float32bits(r.COGDegrees))
		offset += 4

		// Timestamp (int64 LE)
		binary.LittleEndian.PutUint64(buf[offset:], uint64(r.TSUnixMs))
		offset += 8

		// IsScriptedViolator
		if r.IsScriptedViolator {
			buf[offset] = 1
		} else {
			buf[offset] = 0
		}
		offset++
	}

	return buf, nil
}

// UnmarshalBinary deserializes an AISBatch from the compact binary format.
func (b *AISBatch) UnmarshalBinary(data []byte) error {
	if len(data) < 8 {
		return ErrTooShort
	}

	offset := 0

	b.BatchSeq = int32(binary.LittleEndian.Uint32(data[offset:]))
	offset += 4

	recordCount := int(binary.LittleEndian.Uint32(data[offset:]))
	offset += 4

	b.Records = make([]AISRecord, recordCount)

	for i := 0; i < recordCount; i++ {
		r := &b.Records[i]

		// VesselID length
		if offset >= len(data) {
			return ErrTooShort
		}
		vidLen := int(data[offset])
		offset++
		if offset+vidLen > len(data) {
			return ErrTooShort
		}
		r.VesselID = string(data[offset : offset+vidLen])
		offset += vidLen

		// MMSI length
		if offset >= len(data) {
			return ErrTooShort
		}
		mmsiLen := int(data[offset])
		offset++
		if offset+mmsiLen > len(data) {
			return ErrTooShort
		}
		r.MMSI = string(data[offset : offset+mmsiLen])
		offset += mmsiLen

		// Lat
		if offset+8 > len(data) {
			return ErrTooShort
		}
		r.Lat = math.Float64frombits(binary.LittleEndian.Uint64(data[offset:]))
		offset += 8

		// Lon
		if offset+8 > len(data) {
			return ErrTooShort
		}
		r.Lon = math.Float64frombits(binary.LittleEndian.Uint64(data[offset:]))
		offset += 8

		// SOG
		if offset+4 > len(data) {
			return ErrTooShort
		}
		r.SOGKnots = math.Float32frombits(binary.LittleEndian.Uint32(data[offset:]))
		offset += 4

		// COG
		if offset+4 > len(data) {
			return ErrTooShort
		}
		r.COGDegrees = math.Float32frombits(binary.LittleEndian.Uint32(data[offset:]))
		offset += 4

		// Timestamp
		if offset+8 > len(data) {
			return ErrTooShort
		}
		r.TSUnixMs = int64(binary.LittleEndian.Uint64(data[offset:]))
		offset += 8

		// IsScriptedViolator
		if offset >= len(data) {
			return ErrTooShort
		}
		r.IsScriptedViolator = data[offset] == 1
		offset++
	}

	return nil
}

// Errors
type ProtoError string

func (e ProtoError) Error() string { return string(e) }

const ErrTooShort ProtoError = "proto: data too short for deserialization"
